4/06 add the mentor
htmlacademy-javascript/998653-kekstagram-26 pull request #1
Opened 2022-06-04 10:32 UTC by nata07-erbet

Дима! привет!

2022-06-04 18:18 UTC, Dima-Dim requested changes

2022-06-04 18:18 UTC, Dima-Dim commented on Readme.md
> +- Наставник: `Дмитрий Гуляев`.
Отредактируй, пожалуйста, строку Наставник чтобы было по аналогии со строкой Студент. Для этого нужно добавить ссылку на мой профиль https://htmlacademy.ru/profile/dima

2022-06-06 12:43 UTC, nata07-erbet commented on Readme.md
> +- Наставник: `Дмитрий Гуляев`.
Привет! Добавила

2022-06-06 15:45 UTC, Dima-Dim requested changes
Сейчас это выглядит вот так:
https://github.com/htmlacademy-javascript/998653-kekstagram-26/blob/eabf9a73168c00f6d4893f412cb50f81d13052a3/Readme.md
Нужно немного поправить чтобы ссылкой были имя и фамилия.

2022-06-20 12:52 UTC, Dima-Dim requested changes
Теперь это выглядит так https://github.com/htmlacademy-javascript/998653-kekstagram-26/blob/eabf9a73168c00f6d4893f412cb50f81d13052a3/Readme.md
Всё ещё отличается от строки Студент.

2022-06-21 14:31 UTC, merged